import { cp, mkdir, rm } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { resolve } from 'node:path';
import { applyV163CashFixes } from './apply-v163-cash-fixes.mjs';
import { applyV163Cleanup } from './apply-v163-cleanup.mjs';
import { applyV170OfflineWorkflow } from './apply-v170-offline-workflow.mjs';
import { applyV180StockShare } from './apply-v180-stock-share.mjs';
import { applyV190StockColumns } from './apply-v190-stock-columns.mjs';
import { applyV190MonthGuard } from './apply-v190-month-guard.mjs';
import { applyV191StaticStockFooter } from './apply-v191-static-stock-footer.mjs';
import { applyV192FastStockSubmit } from './apply-v192-fast-stock-submit.mjs';
import { applyV193StockFooterFilter } from './apply-v193-stock-footer-filter.mjs';
import { applyV194DirectRelationExport } from './apply-v194-direct-relation-export.mjs';
import { applyV1100SeparateStockActions } from './apply-v1100-separate-stock-actions.mjs';
import { applyV1101StockSharePermission } from './apply-v1101-stock-share-permission.mjs';
import { applyV1103TemplateStockExport } from './apply-v1103-template-stock-export.mjs';
import { applyV1110ExportLock } from './apply-v1110-export-lock.mjs';
import { applyV1111PdfHeaderContrast } from './apply-v1111-pdf-header-contrast.mjs';
import { applyV1112StockSaveRetry } from './apply-v1112-stock-save-retry.mjs';
import { applyV1120IndependentTabDrafts } from './apply-v1120-independent-tab-drafts.mjs';
import { applyV1121RuntimeFix } from './apply-v1121-runtime-fix.mjs';
import { applyV1123NavFooter } from './apply-v1123-nav-footer.mjs';
import { applyV1125SidebarUnlock } from './apply-v1125-sidebar-unlock.mjs';
import { applyV1130StockClosedLoop } from './apply-v1130-stock-closed-loop.mjs';
import { applyV1131FastStockRefresh } from './apply-v1131-fast-stock-refresh.mjs';

const root = resolve(import.meta.dirname, '..');
const dist = resolve(root, 'dist');
await rm(dist, { recursive: true, force: true });
await mkdir(dist, { recursive: true });
await cp(resolve(root, 'public'), dist, { recursive: true });
await cp(resolve(root, 'src'), resolve(dist, 'src'), { recursive: true });
await mkdir(resolve(dist, 'vendor'), { recursive: true });
await cp(resolve(root, 'node_modules/exceljs/dist/exceljs.min.js'), resolve(dist, 'vendor/exceljs.min.js'));
await cp(resolve(root, 'node_modules/pdf-lib/dist/pdf-lib.min.js'), resolve(dist, 'vendor/pdf-lib.min.js'));
await applyV163CashFixes(dist);
await applyV163Cleanup(dist);
await applyV170OfflineWorkflow(dist);
await applyV180StockShare(dist);
await applyV190StockColumns(dist, root);
await applyV190MonthGuard(dist);
await applyV191StaticStockFooter(dist);
await applyV192FastStockSubmit(dist);
await applyV193StockFooterFilter(dist);
await applyV194DirectRelationExport(dist);
await applyV1100SeparateStockActions(dist);
await applyV1101StockSharePermission(dist);
await applyV1103TemplateStockExport(dist, root);
await applyV1110ExportLock(dist, root);
await applyV1111PdfHeaderContrast(dist);
await applyV1112StockSaveRetry(dist);
await applyV1120IndependentTabDrafts(dist);
await applyV1121RuntimeFix(dist);
await applyV1123NavFooter(dist);
await applyV1125SidebarUnlock(dist);
await applyV1130StockClosedLoop(dist);
await applyV1131FastStockRefresh(dist);

for (const relativePath of ['src/main.js', 'src/pages/stock.js', 'src/core/stock-local-export.js', 'src/core/offline-workflow.js']) {
  execFileSync(process.execPath, ['--check', resolve(dist, relativePath)], { stdio: 'inherit' });
}

console.log('Built static app into dist/');
