import { cp, mkdir, rm } from 'node:fs/promises';
import { resolve } from 'node:path';
import { applyV163CashFixes } from './apply-v163-cash-fixes.mjs';
import { applyV163Cleanup } from './apply-v163-cleanup.mjs';
import { applyV170OfflineWorkflow } from './apply-v170-offline-workflow.mjs';
import { applyV180StockShare } from './apply-v180-stock-share.mjs';
import { applyV190StockColumns } from './apply-v190-stock-columns.mjs';
import { applyV190MonthGuard } from './apply-v190-month-guard.mjs';
import { applyV191StaticStockFooter } from './apply-v191-static-stock-footer.mjs';
import { applyV192FastStockSubmit } from './apply-v192-fast-stock-submit.mjs';
import { applyV193StockFooterFilter } from './apply-v193-stock-footer-filter.mjs';

const root = resolve(import.meta.dirname, '..');
const dist = resolve(root, 'dist');
await rm(dist, { recursive: true, force: true });
await mkdir(dist, { recursive: true });
await cp(resolve(root, 'public'), dist, { recursive: true });
await cp(resolve(root, 'src'), resolve(dist, 'src'), { recursive: true });
await applyV163CashFixes(dist);
await applyV163Cleanup(dist);
await applyV170OfflineWorkflow(dist);
await applyV180StockShare(dist);
await applyV190StockColumns(dist, root);
await applyV190MonthGuard(dist);
await applyV191StaticStockFooter(dist);
await applyV192FastStockSubmit(dist);
await applyV193StockFooterFilter(dist);
console.log('Built static app into dist/');
