import { useEffect,useMemo,useState } from 'react'
import { Link,useParams } from 'react-router-dom'
import { opsClient } from '@/api/opsClient'
import { useAuth } from '@/lib/AuthContext'
import { parseOutletIds } from '@/lib/outlets'
import { Button } from '@/components/ui/button'
import { AlertTriangle,ArrowLeft,BookOpen,CheckCircle2,ChevronLeft,ChevronRight,ClipboardCheck,Expand,Loader2,ShieldAlert,Target } from 'lucide-react'

const yes=v=>v===true||String(v).toLowerCase()==='true'
function date(v){if(!v)return'';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString('en-MY')}
function slice(url,index,count){const top=17,band=52/Math.max(count,1),start=top+band*index;return{backgroundImage:`url(${url})`,backgroundSize:'100% auto',backgroundRepeat:'no-repeat',backgroundPosition:`center ${(start/Math.max(100-band,1))*100}%`,aspectRatio:`900 / ${1272*(band/100)}`}}

export default function GuidedSop(){
 const {sopId}=useParams(),{user}=useAuth()
 const [sop,setSop]=useState(null),[steps,setSteps]=useState([]),[assets,setAssets]=useState([]),[acks,setAcks]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[index,setIndex]=useState(0),[saving,setSaving]=useState(false),[full,setFull]=useState(false)
 useEffect(()=>{let off=false;setLoading(true);Promise.all([opsClient.entities.SOP.filter({id:sopId},'',5),opsClient.entities.SOPStep.filter({sop_id:sopId},'step_order',200),opsClient.entities.SOPAsset.filter({sop_id:sopId},'step_id,display_order',300),opsClient.entities.TrainingAcknowledgement.filter({sop_id:sopId,user_email:user.email},'-acknowledged_at',20)]).then(([a,b,c,d])=>{if(off)return;setSop((a||[])[0]||null);setSteps((b||[]).filter(x=>yes(x.active)).sort((x,y)=>Number(x.step_order)-Number(y.step_order)));setAssets((c||[]).filter(x=>yes(x.active)));setAcks(d||[])}).catch(e=>!off&&setError(e.message)).finally(()=>!off&&setLoading(false));return()=>{off=true}},[sopId,user.email])
 useEffect(()=>setIndex(0),[sopId])
 const poster=String(sop?.source_document_url||''),current=steps[index],stepAssets=useMemo(()=>assets.filter(a=>String(a.step_id||'')===String(current?.id||'')),[assets,current?.id]),ack=acks.some(a=>String(a.acknowledged_version)===String(sop?.version_label||sop?.version))
 async function acknowledge(){setSaving(true);try{const row=await opsClient.entities.TrainingAcknowledgement.create({sop_id:sop.id,user_email:user.email,user_name:user.full_name||user.email,outlet_id:user.outlet_id||parseOutletIds(user)[0]||'',acknowledged_version:sop.version_label||String(sop.version||''),status:'acknowledged'});setAcks(x=>[row,...x])}catch(e){setError(e.message)}finally{setSaving(false)}}
 if(loading)return <div className="flex min-h-[60dvh] items-center justify-center"><Loader2 className="h-7 w-7 animate-spin"/></div>
 if(!sop)return <div className="mx-auto max-w-lg p-4"><Link to="/training" className="flex items-center gap-2 text-sm"><ArrowLeft className="h-4 w-4"/>返回 SOP Library</Link><div className="mt-4 rounded-xl bg-destructive/10 p-4 text-sm text-destructive">{error||'SOP not found'}</div></div>
 return <div className="mx-auto max-w-6xl pb-24 md:p-6 md:pb-10">
  <header className="border-b bg-background p-4 md:rounded-t-2xl md:border"><div className="flex gap-3"><Link to="/training" className="flex h-9 w-9 items-center justify-center rounded-xl border"><ArrowLeft className="h-4 w-4"/></Link><div className="min-w-0"><div className="flex gap-2"><span className="rounded-full bg-primary/15 px-2 py-1 text-[10px] font-bold text-primary">{sop.sop_code}</span><span className="py-1 text-[10px] text-muted-foreground">Version {sop.version_label||sop.version}</span></div><h1 className="mt-1 text-xl font-bold leading-7 md:text-2xl">{sop.title}</h1><p className="text-xs text-muted-foreground">{sop.department} · {sop.station} · Effective {date(sop.effective_date)}</p></div></div></header>
  {error&&<div className="m-4 rounded-xl bg-destructive/10 p-3 text-sm text-destructive md:mx-0">{error}</div>}

  <div className="md:hidden"><div className="space-y-3 p-4">
   <div className="rounded-2xl border bg-card p-4"><div className="flex justify-between text-xs"><b>引导阅读</b><span>步骤 {index+1}/{Math.max(steps.length,1)}</span></div><div className="mt-2 h-2 rounded bg-muted"><div className="h-full rounded bg-primary" style={{width:`${steps.length?(index+1)/steps.length*100:100}%`}}/></div>{sop.summary&&<p className="mt-3 text-sm leading-6 text-muted-foreground">{sop.summary}</p>}</div>
   {current?<GuideStep step={current} index={index} total={steps.length} poster={poster} assets={stepAssets}/>:<div className="rounded-2xl border p-6 text-center text-sm">No active steps.</div>}
   {index===steps.length-1&&<Finish sop={sop} ack={ack} saving={saving} onAck={acknowledge}/>} 
   {poster&&<button onClick={()=>setFull(true)} className="flex w-full items-center gap-3 rounded-2xl border p-3 text-left"><Expand className="h-5 w-5 text-primary"/><span className="flex-1"><b className="block text-sm">查看完整海报</b><small className="text-muted-foreground">Tablet, desktop or printing</small></span><ChevronRight className="h-4 w-4"/></button>}
  </div>{steps.length>0&&<div className="fixed inset-x-0 bottom-[calc(4.6rem+env(safe-area-inset-bottom))] z-30 border-t bg-background/95 p-3 backdrop-blur"><div className="mx-auto grid max-w-lg grid-cols-2 gap-2"><Button variant="outline" disabled={index===0} onClick={()=>setIndex(x=>Math.max(0,x-1))}><ChevronLeft className="mr-1 h-4 w-4"/>上一步</Button><Button disabled={index>=steps.length-1} onClick={()=>setIndex(x=>Math.min(steps.length-1,x+1))}>{index>=steps.length-1?'阅读完成':'下一步'}<ChevronRight className="ml-1 h-4 w-4"/></Button></div></div>}</div>

  <div className="hidden gap-6 rounded-b-2xl border border-t-0 bg-muted/10 p-6 md:grid md:grid-cols-[minmax(320px,.8fr)_minmax(0,1.2fr)]"><aside>{poster?<div className="sticky top-20 overflow-hidden rounded-2xl border bg-card"><img src={poster} alt={sop.title} className="w-full"/><button onClick={()=>setFull(true)} className="flex w-full items-center justify-center gap-2 border-t p-3 text-sm font-semibold"><Expand className="h-4 w-4"/>Enlarge full poster</button></div>:<div className="rounded-2xl border border-dashed p-8 text-center text-sm">Poster will appear here.</div>}</aside><main className="space-y-4"><Intro sop={sop}/>{steps.map((s,i)=><DesktopStep key={s.id} step={s} index={i} assets={assets.filter(a=>String(a.step_id||'')===String(s.id))}/>)}<Finish sop={sop} ack={ack} saving={saving} onAck={acknowledge}/></main></div>
  {full&&poster&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/90 p-3" onClick={()=>setFull(false)}><button className="absolute right-4 top-4 rounded-full bg-white/15 px-3 py-2 text-sm text-white">关闭</button><img src={poster} alt={sop.title} className="max-h-full max-w-full object-contain" onClick={e=>e.stopPropagation()}/></div>}
 </div>
}
function Intro({sop}){return <div className="space-y-3 rounded-2xl border bg-card p-4"><div className="flex gap-3"><Target className="mt-1 h-5 w-5 text-primary"/><div><b>Purpose</b><p className="mt-1 text-sm leading-6 text-muted-foreground">{sop.purpose||sop.summary}</p></div></div>{sop.scope&&<div className="border-t pt-3"><b className="text-xs text-muted-foreground">SCOPE</b><p className="mt-1 text-sm leading-6">{sop.scope}</p></div>}{sop.safety_notes&&<div className="flex gap-2 rounded-xl border border-amber-300 bg-amber-50 p-3 text-sm leading-6"><ShieldAlert className="mt-1 h-4 w-4 shrink-0"/>{sop.safety_notes}</div>}</div>}
function GuideStep({step,index,total,poster,assets}){return <article className="overflow-hidden rounded-2xl border bg-card"><div className="bg-primary p-4 text-primary-foreground"><small className="font-bold opacity-80">STEP {index+1} OF {total}</small><h2 className="mt-1 text-lg font-bold">{step.step_title}</h2></div>{poster&&<div className="border-b bg-muted/20 p-3"><div className="w-full rounded-xl border bg-white" style={slice(poster,index,total)}/></div>}{assets.length>0&&<AssetGrid assets={assets}/>}<div className="space-y-3 p-4">{step.instruction&&<Block icon={BookOpen} label="怎么做 / HOW TO DO" text={step.instruction}/>} {step.warning&&<Block icon={AlertTriangle} label="不及格 / FAIL IF" text={step.warning} tone="bad"/>}{step.quality_check&&<Block icon={ClipboardCheck} label="完成标准 / PASS" text={step.quality_check} tone="good"/>}</div></article>}
function DesktopStep({step,index,assets}){return <article className="overflow-hidden rounded-2xl border bg-card"><div className="flex gap-3 p-4"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-primary font-bold text-primary-foreground">{index+1}</span><div><small className="font-semibold text-muted-foreground">{step.section_title}</small><h3 className="text-lg font-bold">{step.step_title}</h3></div></div>{assets.length>0&&<AssetGrid assets={assets}/>}<div className="grid gap-3 border-t p-4 lg:grid-cols-3">{step.instruction&&<Block icon={BookOpen} label="HOW TO DO" text={step.instruction}/>} {step.warning&&<Block icon={AlertTriangle} label="FAIL IF" text={step.warning} tone="bad"/>}{step.quality_check&&<Block icon={ClipboardCheck} label="PASS STANDARD" text={step.quality_check} tone="good"/>}</div></article>}
function Block({icon:Icon,label,text,tone}){return <div className={`rounded-xl border p-3 ${tone==='bad'?'border-rose-200 bg-rose-50':tone==='good'?'border-emerald-200 bg-emerald-50':'bg-muted/25'}`}><div className="flex items-center gap-2"><Icon className="h-4 w-4"/><b className="text-[11px]">{label}</b></div><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{text}</p></div>}
function AssetGrid({assets}){return <div className="grid grid-cols-2 gap-2 border-y bg-muted/20 p-3">{assets.map(a=>a.asset_type==='image'?<img key={a.id} src={a.thumbnail_url||a.file_url} alt={a.caption||a.file_name} className="aspect-[4/3] w-full rounded-xl border bg-white object-contain"/>:<a key={a.id} href={a.file_url} target="_blank" rel="noreferrer" className="rounded-xl border bg-white p-3 text-xs font-semibold">{a.caption||a.file_name}</a>)}</div>}
function Finish({sop,ack,saving,onAck}){return <div className="rounded-2xl border bg-card p-4"><div className="flex gap-3"><CheckCircle2 className="h-6 w-6 text-emerald-600"/><div><b>Chapter complete</b><p className="mt-1 text-sm leading-6 text-muted-foreground">确认你已经看过每一步的做法、不及格情况和完成标准。SOP 用于学习与查询，不会替代每日 Task。</p></div></div><div className="mt-4">{ack?<div className="rounded-xl bg-emerald-100 p-3 text-center text-sm font-semibold text-emerald-800">Version {sop.version_label||sop.version} acknowledged</div>:<Button className="w-full" onClick={onAck} disabled={saving}>{saving&&<Loader2 className="mr-2 h-4 w-4 animate-spin"/>}我已阅读并理解</Button>}</div></div>}
