import { useEffect,useMemo,useRef,useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { opsClient } from '@/api/opsClient'
import { useAuth } from '@/lib/AuthContext'
import { parseOutletIds,outletLabel } from '@/lib/outlets'
import { todayStr } from '@/lib/ops-helpers'
import AppDrawer from '@/components/AppDrawer'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { AlertTriangle,BookOpen,Camera,Check,CheckCircle2,ChevronDown,ChevronRight,Clock,Loader2,Lock,RefreshCw,Trash2 } from 'lucide-react'
import { watermarkTaskPhoto } from '@/lib/watermark-image'

const shifts=['MORNING','DAILY','NIGHT']
const filters=[['all','全部'],['open','待完成'],['done','已完成'],['locked','已锁定']]
const cn=(o,k,f='')=>o?.[`${k}_cn`]||o?.[k]||f
const en=(o,k)=>o?.[`${k}_en`]||''
const flat=t=>(t.config?.sections||[]).flatMap(s=>s.items||[])
const mapResponses=t=>Object.fromEntries((t.responses||[]).map(r=>[String(r.item_id),{...r}]))
function time(v){if(!v)return'';return new Intl.DateTimeFormat('en-MY',{timeZone:'Asia/Kuching',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v))}
function parts(v){return Object.fromEntries(String(v||'').split(';').filter(Boolean).map(x=>{const i=x.indexOf('=');return i<0?['FREQ',x.toUpperCase()]:[x.slice(0,i).toUpperCase(),x.slice(i+1).toUpperCase()]}))}
function occurs(t,d){const p=parts(t.recurrence_rule),f=p.FREQ||'DAILY',x=new Date(`${d}T00:00:00Z`);if(f==='DAILY')return true;if(f==='WEEKLY')return String(p.BYDAY||'').split(',').includes(['SU','MO','TU','WE','TH','FR','SA'][x.getUTCDay()]);if(f==='MONTHLY')return String(p.BYMONTHDAY||'1').split(',').map(Number).includes(x.getUTCDate());return true}
function result(i,r){if(r?.value===''||r?.value==null)return'incomplete';return(i.fail_values||[]).map(String).includes(String(r.value))?'fail':'pass'}
function status(t){const s=String(t.access_state||'').toUpperCase();return s==='DONE'?'已完成':s==='NOT_OPEN'?'未开放':s==='LOCKED'?'已锁定':s==='OVERDUE'?'已逾时':'可执行'}
function visible(t,f){if(f==='all')return true;if(f==='done')return String(t.status).toLowerCase()==='done';if(f==='locked')return String(t.access_state).toUpperCase()==='LOCKED';return String(t.status).toLowerCase()!=='done'&&String(t.access_state).toUpperCase()!=='LOCKED'}
function photoUrl(r){return r.file_url||`${opsClient.apiBaseUrl}/api/files/${encodeURIComponent(r.drive_file_id||'')}`}

export default function OperationalTasksV2(){
 const {user}=useAuth(),nav=useNavigate(),allowed=parseOutletIds(user)
 const [outlets,setOutlets]=useState([]),[outletId,setOutletId]=useState(user.outlet_id||allowed[0]||''),[date,setDate]=useState(todayStr()),[data,setData]=useState({tasks:[],task_photos:[]}),[selected,setSelected]=useState(''),[filter,setFilter]=useState('all'),[loading,setLoading]=useState(true),[error,setError]=useState('')
 async function load(refresh=false){setLoading(true);setError('');try{setData(await opsClient.tasks.operationalBootstrap({outletId,date,refresh}))}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{opsClient.entities.Outlet.list('name',100).then(r=>setOutlets((r||[]).filter(x=>allowed.includes(String(x.id))))).catch(()=>{})},[user.outlet_ids])
 useEffect(()=>{if(outletId)load()},[outletId,date])
 async function act(id,action,payload={}){const r=await opsClient.tasks.operationalAction({task_id:id,outlet_id:outletId,date,action,...payload});setData(d=>({...d,tasks:d.tasks.map(t=>t.id===id?r.task:t)}));return r.task}
 const tasks=useMemo(()=>(data.tasks||[]).filter(t=>occurs(t,date)),[data.tasks,date]),chosen=tasks.find(t=>t.id===selected),outlet=outlets.find(x=>String(x.id)===String(outletId))
 return <div className="mx-auto max-w-lg space-y-4 p-4 pb-24">
  <div className="flex items-start justify-between"><div><h1 className="text-xl font-bold">今日任务</h1><p className="text-xs text-muted-foreground">Daily Tasks · {outletLabel(outlet,outletId)}</p></div><Button size="icon" variant="outline" onClick={()=>load(true)}><RefreshCw className="h-4 w-4"/></Button></div>
  {outlets.length>1&&<select className="h-10 w-full rounded-md border bg-background px-3" value={outletId} onChange={e=>setOutletId(e.target.value)}>{outlets.map(o=><option key={o.id} value={o.id}>{outletLabel(o,o.id)}</option>)}</select>}
  <Input type="date" value={date} onChange={e=>setDate(e.target.value)}/>
  <div className="flex gap-2 overflow-auto">{filters.map(([v,l])=><button key={v} onClick={()=>setFilter(v)} className={`whitespace-nowrap rounded-full px-3 py-1.5 text-xs font-semibold ${filter===v?'bg-primary text-primary-foreground':'bg-muted'}`}>{l}</button>)}</div>
  {error&&<div className="rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{error}</div>}
  {loading?<div className="flex justify-center py-12"><Loader2 className="animate-spin"/></div>:shifts.map(shift=>{const rows=tasks.filter(t=>String(t.config?.schedule?.shift_id||t.period).toUpperCase()===shift&&visible(t,filter));if(!rows.length)return null;return <section key={shift} className="space-y-2"><div className="border-b pb-2"><b className="text-sm">{shift==='MORNING'?'早班':shift==='NIGHT'?'晚班':'日间'}</b><span className="ml-2 text-xs text-muted-foreground">{rows.length} tasks</span></div>{rows.map(t=><TaskCard key={t.id} t={t} onOpen={async()=>{if(t.status==='pending'&&['OPEN','OVERDUE'].includes(String(t.access_state).toUpperCase()))await act(t.id,'start');setSelected(t.id)}}/>)}</section>})}
  <AppDrawer open={!!chosen} onOpenChange={o=>!o&&setSelected('')} title={chosen?cn(chosen.config,'title',chosen.title):'任务'} subtitle={chosen?en(chosen.config,'title'):''} heightClass="h-[94dvh]">{chosen&&<TaskForm t={chosen} outletId={outletId} outletName={outletLabel(outlet,outletId)} photos={(data.task_photos||[]).filter(p=>p.task_id===chosen.id&&!p.deleted_at&&String(p.status||'active').toLowerCase()!=='deleted')} onAct={async(a,p)=>{const u=await act(chosen.id,a,p);setSelected(u.id)}} reload={()=>load(true)} openSop={id=>nav(`/sop/${id}`)} error={setError}/>}</AppDrawer>
 </div>
}
function TaskCard({t,onOpen}){const items=flat(t),done=Number(t.checklist_completed||0),locked=['NOT_OPEN','LOCKED'].includes(String(t.access_state).toUpperCase());return <button onClick={onOpen} className="w-full rounded-2xl border bg-card p-4 text-left shadow-sm"><div className="flex gap-3"><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${locked?'bg-muted':'bg-primary/15'}`}>{locked?<Lock className="h-5 w-5"/>:<Clock className="h-5 w-5 text-primary"/>}</span><div className="min-w-0 flex-1"><b className="block text-sm">{cn(t.config,'title',t.title)}</b><span className="block text-xs text-muted-foreground">{en(t.config,'title')}</span><span className="mt-1 block text-[11px] text-muted-foreground">{time(t.opens_at)}–{time(t.due_at)} · {t.config?.estimated_minutes||0} min</span></div><span className="rounded-full bg-muted px-2 py-1 text-[10px] font-semibold">{status(t)}</span></div><div className="mt-3 flex items-center gap-2"><div className="h-1.5 flex-1 rounded bg-muted"><div className="h-full rounded bg-primary" style={{width:`${items.length?done/items.length*100:0}%`}}/></div><span className="text-[11px]">{done}/{items.length}</span><ChevronRight className="h-4 w-4"/></div></button>}
function TaskForm({t,outletId,outletName,photos,onAct,reload,openSop,error}){
 const c=t.config||{},items=flat(t),groups=t.photo_requirements||c.photo_groups||[],input=useRef({}),[responses,setResponses]=useState(()=>mapResponses(t)),[notes,setNotes]=useState(t.completion_notes||''),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(''),[deleting,setDeleting]=useState(''),readonly=['NOT_OPEN','LOCKED','DONE'].includes(String(t.access_state).toUpperCase()),sop=t.sop_id||c.sop_id
 useEffect(()=>{setResponses(mapResponses(t));setNotes(t.completion_notes||'')},[t.id,t.version,t.updated_date])
 const update=(id,p)=>setResponses(r=>({...r,[id]:{item_id:id,value:'',remark:'',corrective_action:'',...(r[id]||{}),...p}}))
 async function save(action){setBusy(true);try{await onAct(action,{responses:Object.values(responses),completion_notes:notes})}catch(e){error(e.message)}finally{setBusy(false)}}
 async function upload(g,file){if(!file)return;setUploading(g.id);try{const w=await watermarkTaskPhoto(file,{capturedAt:new Date()}),u=await opsClient.integrations.Core.UploadFile({file:w.file,folderType:'Task Evidence',outletName,outletId});await opsClient.entities.TaskPhoto.create({outlet_id:outletId,task_id:t.id,template_id:t.template_id,photo_type:`checklist:${g.id}`,drive_file_id:u.drive_file_id||'',file_name:u.file_name||w.file.name,file_url:u.file_url||'',caption:cn(g,'name'),status:'active',mime_type:u.mime_type||w.file.type,file_size:Number(u.file_size||w.file.size),captured_at:w.capturedAt,watermark_text:w.watermarkText},{year:Number(t.due_date.slice(0,4))});await reload()}catch(e){error(e.message)}finally{setUploading('');if(input.current[g.id])input.current[g.id].value=''}}
 async function del(p){if(!confirm('删除这张照片并重新拍摄？'))return;setDeleting(p.id);try{try{await opsClient.entities.TaskPhoto.delete(p.id,{year:Number(t.due_date.slice(0,4))})}catch(deleteError){await opsClient.entities.TaskPhoto.update(p.id,{status:'deleted'},{year:Number(t.due_date.slice(0,4))})}await reload()}catch(e){error(e.message||'无法删除照片')}finally{setDeleting('')}}
 return <div className="flex min-h-0 flex-1 flex-col"><div className="min-h-0 flex-1 space-y-4 overflow-auto p-4 pb-8">
  <div className="rounded-2xl border bg-muted/25 p-3"><b>{cn(c.schedule,'shift_name')}</b><p className="text-xs text-muted-foreground">开放 {time(t.opens_at)} · 截止 {time(t.due_at)}</p></div>
  {cn(c,'completion_standard')&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-3"><b className="text-xs">完成标准</b><p className="mt-1 text-sm leading-6">{cn(c,'completion_standard')}</p></div>}
  {sop&&<button onClick={()=>openSop(sop)} className="flex w-full items-center gap-3 rounded-2xl border p-3 text-left"><BookOpen className="h-5 w-5 text-primary"/><span className="flex-1"><b className="block text-sm">不确定怎样做？查看标准做法</b><small className="text-muted-foreground">SOP guide</small></span><ChevronRight className="h-4 w-4"/></button>}
  {readonly&&String(t.access_state).toUpperCase()!=='DONE'&&<div className="flex gap-2 rounded-xl bg-amber-50 p-3 text-sm"><AlertTriangle className="h-4 w-4"/>任务未开放或已锁定。</div>}
  {(c.sections||[]).map(s=><section key={s.id} className="space-y-2"><div><b className="text-sm">{cn(s,'name')}</b><p className="text-[11px] text-muted-foreground">{en(s,'name')}</p></div>{(s.items||[]).map(i=><Item key={i.id} i={i} r={responses[i.id]||{item_id:i.id,value:''}} readonly={readonly} update={p=>update(i.id,p)} standard={cn(c,'completion_standard')}/>)}</section>)}
  {groups.length>0&&<section className="space-y-2"><div><b className="text-sm">照片留证</b><p className="text-[11px] text-muted-foreground">只在规则要求时拍摄。</p></div>{groups.map(g=>{const rows=photos.filter(p=>p.photo_type===`checklist:${g.id}`),required=String(g.rule).toUpperCase()==='REQUIRED'||flat(t).filter(i=>i.photo_group_id===g.id).some(i=>result(i,responses[i.id])==='fail');return <div key={g.id} className="rounded-2xl border p-3"><div className="flex justify-between gap-2"><div><b className="text-sm">{cn(g,'name')}</b><p className="text-xs text-muted-foreground">{cn(g,'sample_caption')}</p></div><small className="whitespace-nowrap">{required?(rows.length<Number(g.min_photos||1)?`还需 ${Number(g.min_photos||1)-rows.length} 张`:`已完成 · ${rows.length}/${g.max_photos||1} 张`):`异常时拍 · ${rows.length}/${g.max_photos||1} 张`}</small></div>{rows.length>0&&<div className="mt-2 grid grid-cols-2 gap-2">{rows.map(p=><div key={p.id} className="relative"><img src={photoUrl(p)} className="aspect-[4/3] w-full rounded-xl object-cover" alt="Task evidence"/>{!readonly&&<button type="button" disabled={deleting===p.id} onClick={()=>del(p)} className="absolute right-1 top-1 rounded-full bg-black/70 p-2 text-white disabled:opacity-60" aria-label="Delete photo">{deleting===p.id?<Loader2 className="h-3 w-3 animate-spin"/>:<Trash2 className="h-3 w-3"/>}</button>}</div>)}</div>}{!readonly&&<><Button size="sm" variant="outline" className="mt-2" disabled={uploading===g.id||rows.length>=Number(g.max_photos||1)} onClick={()=>input.current[g.id]?.click()}>{uploading===g.id?<Loader2 className="mr-1 h-4 w-4 animate-spin"/>:<Camera className="mr-1 h-4 w-4"/>}{rows.length?`加拍照片 ${rows.length}/${g.max_photos||1}`:'拍照'}</Button><input ref={n=>input.current[g.id]=n} type="file" accept="image/*" capture="environment" className="hidden" onChange={e=>upload(g,e.target.files?.[0])}/></>}</div>})}</section>}
  <Textarea rows={3} value={notes} disabled={readonly} onChange={e=>setNotes(e.target.value)} placeholder="异常或交接备注（选填）"/>
 </div>{!readonly&&<div className="grid grid-cols-2 gap-2 border-t bg-background p-4"><Button variant="outline" onClick={()=>save('save')} disabled={busy}>保存进度</Button><Button onClick={()=>save('complete')} disabled={busy}><CheckCircle2 className="mr-1 h-4 w-4"/>完成任务</Button></div>}</div>}
function Item({i,r,readonly,update,standard}){const fail=result(i,r)==='fail',type=String(i.response_type||'').toUpperCase(),opts=i.options||[];return <div className={`rounded-2xl border p-3 ${fail?'border-rose-300 bg-rose-50':'bg-card'}`}><div className="flex gap-2"><span className={`flex h-6 w-6 items-center justify-center rounded-full border ${result(i,r)==='pass'?'bg-emerald-500 text-white':''}`}>{result(i,r)==='pass'?<Check className="h-4 w-4"/>:null}</span><div className="flex-1"><b className="block text-sm">{cn(i,'name')}</b><small className="text-muted-foreground">{en(i,'name')}</small></div></div><div className="mt-3">{type==='TEXT'?<Textarea rows={3} disabled={readonly} value={r.value||''} onChange={e=>update({value:e.target.value})} placeholder={cn(i,'placeholder','填写数量与状态说明')}/>:type==='CHECKBOX'?<button disabled={readonly} onClick={()=>update({value:r.value==='Done'?'':'Done'})} className={`w-full rounded-xl border p-2.5 text-sm font-semibold ${r.value==='Done'?'border-emerald-500 bg-emerald-50':''}`}>{r.value==='Done'?'✓ 已完成 / Done':'完成这一项 / Mark done'}</button>:<div className={`grid gap-2 ${opts.length>2?'grid-cols-3':'grid-cols-2'}`}>{opts.map(o=><button key={o} disabled={readonly} onClick={()=>update({value:o})} className={`rounded-xl border p-2 text-xs font-semibold ${r.value===o?(i.fail_values||[]).includes(o)?'border-rose-500 bg-rose-50':'border-primary bg-primary/10':''}`}>{o}</button>)}</div>}</div>{(cn(i,'instruction')||standard)&&<details className="mt-2 rounded-xl bg-muted/30 p-2"><summary className="flex cursor-pointer list-none justify-between text-xs font-semibold">查看简单说明<ChevronDown className="h-4 w-4"/></summary><p className="mt-2 text-xs leading-5">{cn(i,'instruction')}</p><p className="mt-2 text-xs"><b>及格：</b>{cn(i,'completion_standard')||standard}</p></details>}{fail&&<div className="mt-2 space-y-2"><Input value={r.remark||''} onChange={e=>update({remark:e.target.value})} placeholder="异常说明"/><Textarea rows={2} value={r.corrective_action||''} onChange={e=>update({corrective_action:e.target.value})} placeholder="怎样处理／已通知谁"/></div>}</div>}
