import { handleStockD1 } from '../_shared/stock-d1.js';

const ALLOWED_GAS_HOSTS = new Set(['script.google.com', 'script.googleusercontent.com']);

export async function onRequestPost(context) {
  try {
    const body = await context.request.json();
    const service = body.service === 'cash' ? 'cash' : 'stock';
    const targetUrl = String(service === 'stock' ? context.env.STOCK_GAS_URL || '' : context.env.CASH_GAS_URL || '').trim();
    const secret = String(service === 'stock' ? context.env.STOCK_GAS_SECRET || '' : context.env.CASH_GAS_SECRET || '');
    const payload = { ...(body.payload || {}) };

    if (service === 'stock' && payload.action === 'importStockSetup') {
      const hasSetup = payload.setup && Array.isArray(payload.setup.sheets);
      if (!hasSetup && payload.setupJson) {
        try {
          const parsedSetup = JSON.parse(String(payload.setupJson));
          if (parsedSetup && Array.isArray(parsedSetup.sheets)) payload.setup = parsedSetup;
        } catch {
          return json({ ok: false, error: 'Stock Setup JSON could not be read. Export a fresh Stock Setup DB file and import it again.' }, 400);
        }
      }
      if (!payload.setup || !Array.isArray(payload.setup.sheets)) {
        return json({ ok: false, error: 'Stock Setup data was missing before D1 import.' }, 400);
      }
    }

    if (service === 'cash' && !String(payload.outlet || '').trim()) {
      return json({ ok: false, error: 'Missing FeedMe Outlet ID. Open Cash Count from the outlet link generated by FeedMe Insights.' }, 400);
    }

    if (targetUrl) {
      const parsed = new URL(targetUrl);
      if (!ALLOWED_GAS_HOSTS.has(parsed.hostname) || !parsed.pathname.endsWith('/exec')) {
        return json({ ok: false, error: 'Only deployed Google Apps Script /exec URLs are allowed' }, 400);
      }
    }

    if (service === 'stock' && context.env.STOCK_DB && payload.action === 'clearStockCounts') {
      return json(await clearStockCounts(context.env.STOCK_DB, payload), 200, 0);
    }

    if (service === 'stock' && context.env.STOCK_DB) {
      const d1Result = await handleStockD1({ context, payload, targetUrl, secret });
      if (d1Result?.handled) {
        const data = withIntegration(d1Result.data, context.env, 'cloudflare-d1');
        return json(data, d1Result.status || 200, d1Result.ttl || 0);
      }
    }

    if (!targetUrl || !secret) {
      return json({
        ok: false,
        error: `${service === 'stock' ? 'Stock' : 'Cash'} connection is missing from Cloudflare Production Variables`
      }, 400);
    }

    const gasPayload = { ...payload, secret };
    const descriptor = cacheDescriptor(service, gasPayload);
    const edgeCache = globalThis.caches?.default;
    if (descriptor && edgeCache && !gasPayload.refresh) {
      const cached = await edgeCache.match(descriptor.request);
      if (cached) return cached;
    }

    const gasResponse = await fetch(targetUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'text/plain;charset=utf-8' },
      body: JSON.stringify(gasPayload),
      redirect: 'follow'
    });
    const text = await gasResponse.text();
    let data;
    try {
      data = JSON.parse(text);
    } catch {
      const label = service === 'stock' ? 'Stock' : 'Cash';
      return json({
        ok: false,
        error: `${label} GAS did not return JSON. Deploy the Apps Script web app as a new version with access set to Anyone.`,
        status: gasResponse.status
      }, 502);
    }

    if (data.ok && data.saved && !data.duplicate && edgeCache) {
      context.waitUntil(invalidateBootstrapCache(edgeCache, service, gasPayload));
    }
    data = withIntegration(data, context.env, 'google-apps-script');
    const response = json(data, gasResponse.ok ? 200 : 502, descriptor?.ttl || 0);
    if (descriptor && edgeCache && data.ok && gasResponse.ok) {
      context.waitUntil(edgeCache.put(descriptor.request, response.clone()));
    }
    return response;
  } catch (error) {
    return json({ ok: false, error: String(error?.message || error) }, 500);
  }
}

async function clearStockCounts(db, payload) {
  const outlet = String(payload.outlet || payload.outletId || 'RR-KCH').trim() || 'RR-KCH';
  const monthKey = normalizeMonth(payload.monthKey || payload.businessDate);
  const sectionName = String(payload.sectionName || '').trim();
  const weekIndex = Number(payload.weekIndex || 0);
  const now = Date.now();

  const statements = [];
  if (sectionName && weekIndex > 0) {
    statements.push(db.prepare('DELETE FROM stock_values WHERE outlet_id = ? AND month_key = ? AND sheet_name = ? AND week_index = ?').bind(outlet, monthKey, sectionName, weekIndex));
  } else if (sectionName) {
    statements.push(db.prepare('DELETE FROM stock_values WHERE outlet_id = ? AND month_key = ? AND sheet_name = ?').bind(outlet, monthKey, sectionName));
  } else {
    statements.push(db.prepare('DELETE FROM stock_values WHERE outlet_id = ? AND month_key = ?').bind(outlet, monthKey));
  }
  statements.push(db.prepare('DELETE FROM stock_submissions WHERE outlet_id = ? AND month_key = ?').bind(outlet, monthKey));
  statements.push(db.prepare('DELETE FROM stock_sync_queue WHERE outlet_id = ? AND month_key = ?').bind(outlet, monthKey));
  statements.push(db.prepare('DELETE FROM stock_snapshots WHERE outlet_id = ? AND month_key = ?').bind(outlet, monthKey));
  await db.batch(statements);

  return { ok: true, cleared: true, outlet, monthKey, sectionName, weekIndex, clearedAt: now, dataSource: 'cloudflare-d1' };
}

function normalizeMonth(value) {
  const text = String(value || '');
  const match = /^(\d{4})-(\d{2})/.exec(text);
  if (match) return `${match[1]}-${match[2]}`;
  return new Date().toISOString().slice(0, 7);
}

function withIntegration(data, env, source) {
  return {
    ...(data || {}),
    integration: {
      statvara: env.STATVARA_WEBHOOK_URL ? 'reserved' : 'reserved',
      storageProvider: env.FILE_STORAGE_PROVIDER || 'google_drive',
      stockDataSource: source
    }
  };
}

function cacheDescriptor(service, payload) {
  const action = String(payload.action || '');
  let ttl = 0;
  if (action === 'getStandaloneCashBootstrap' || action === 'getBootstrap') ttl = 90;
  else if (action === 'getStandaloneCashDashboard' || action === 'getStockDashboard') ttl = 45;
  if (!ttl) return null;
  const params = new URLSearchParams({
    service,
    action,
    outlet: String(payload.outlet || ''),
    businessDate: String(payload.businessDate || ''),
    dateFrom: String(payload.dateFrom || ''),
    dateTo: String(payload.dateTo || '')
  });
  return {
    ttl,
    request: new Request(`https://operations-cache.internal/read?${params.toString()}`, { method: 'GET' })
  };
}

async function invalidateBootstrapCache(cache, service, payload) {
  const action = service === 'cash' ? 'getStandaloneCashBootstrap' : 'getBootstrap';
  const params = new URLSearchParams({
    service,
    action,
    outlet: String(payload.outlet || ''),
    businessDate: String(payload.businessDate || ''),
    dateFrom: '',
    dateTo: ''
  });
  await cache.delete(new Request(`https://operations-cache.internal/read?${params.toString()}`, { method: 'GET' }));
}

function json(value, status = 200, ttl = 0) {
  return new Response(JSON.stringify(value), {
    status,
    headers: {
      'Content-Type': 'application/json;charset=utf-8',
      'Cache-Control': ttl > 0 ? `public, max-age=0, s-maxage=${ttl}` : 'no-store'
    }
  });
}
