import { handleStockD1 } from '../_shared/stock-d1.js';

const ALLOWED_GAS_HOSTS = new Set(['script.google.com', 'script.googleusercontent.com']);
const REQUIRED_STOCK_SETUP_SECTIONS = ['Inventory', 'Untensil PG1', 'Utensil PG2', 'Stationary'];

export async function onRequestPost(context) {
  try {
    const body = await context.request.json();
    const service = body.service === 'cash' ? 'cash' : 'stock';
    const targetUrl = String(service === 'stock' ? context.env.STOCK_GAS_URL || '' : context.env.CASH_GAS_URL || '').trim();
    const secret = String(service === 'stock' ? context.env.STOCK_GAS_SECRET || '' : context.env.CASH_GAS_SECRET || '');
    const payload = { ...(body.payload || {}) };

    if (service === 'stock' && payload.action === 'importStockSetup') {
      if (!context.env.STOCK_DB) {
        return json({ ok: false, error: 'Cloudflare D1 binding STOCK_DB is missing.' }, 400);
      }
      const imported = await importStockSetupDirect(context.env.STOCK_DB, payload);
      return json(withIntegration(imported, context.env, 'cloudflare-d1-stock-setup'), 200, 0);
    }

    if (service === 'cash' && !String(payload.outlet || '').trim()) {
      return json({ ok: false, error: 'Missing FeedMe Outlet ID. Open Cash Count from the outlet link generated by FeedMe Insights.' }, 400);
    }

    if (targetUrl) {
      const parsed = new URL(targetUrl);
      if (!ALLOWED_GAS_HOSTS.has(parsed.hostname) || !parsed.pathname.endsWith('/exec')) {
        return json({ ok: false, error: 'Only deployed Google Apps Script /exec URLs are allowed' }, 400);
      }
    }

    if (service === 'stock' && context.env.STOCK_DB && payload.action === 'clearStockCounts') {
      return json(await clearStockCounts(context.env.STOCK_DB, payload), 200, 0);
    }

    if (service === 'stock' && context.env.STOCK_DB) {
      const d1Result = await handleStockD1({ context, payload, targetUrl, secret });
      if (d1Result?.handled) {
        const identified = await decorateStockOutletIdentity(context.env.STOCK_DB, payload, d1Result.data);
        const data = withIntegration(identified, context.env, 'cloudflare-d1');
        return json(data, d1Result.status || 200, d1Result.ttl || 0);
      }
    }

    if (!targetUrl || !secret) {
      return json({
        ok: false,
        error: `${service === 'stock' ? 'Stock' : 'Cash'} connection is missing from Cloudflare Production Variables`
      }, 400);
    }

    const gasPayload = { ...payload, secret };
    const descriptor = cacheDescriptor(service, gasPayload);
    const edgeCache = globalThis.caches?.default;
    if (descriptor && edgeCache && !gasPayload.refresh) {
      const cached = await edgeCache.match(descriptor.request);
      if (cached) return cached;
    }

    const gasResponse = await fetch(targetUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'text/plain;charset=utf-8' },
      body: JSON.stringify(gasPayload),
      redirect: 'follow'
    });
    const text = await gasResponse.text();
    let data;
    try {
      data = JSON.parse(text);
    } catch {
      const label = service === 'stock' ? 'Stock' : 'Cash';
      return json({
        ok: false,
        error: `${label} GAS did not return JSON. Deploy the Apps Script web app as a new version with access set to Anyone.`,
        status: gasResponse.status
      }, 502);
    }

    if (data.ok && data.saved && !data.duplicate && edgeCache) {
      context.waitUntil(invalidateBootstrapCache(edgeCache, service, gasPayload));
    }
    data = withIntegration(data, context.env, 'google-apps-script');
    const response = json(data, gasResponse.ok ? 200 : 502, descriptor?.ttl || 0);
    if (descriptor && edgeCache && data.ok && gasResponse.ok) {
      context.waitUntil(edgeCache.put(descriptor.request, response.clone()));
    }
    return response;
  } catch (error) {
    return json({ ok: false, error: String(error?.message || error) }, 500);
  }
}

async function importStockSetupDirect(db, payload) {
  const setup = resolveStockSetupPayload(payload);
  const outletId = String(payload.outlet || payload.outletId || setup.outletId || setup.outlet || 'RR-KCH').trim() || 'RR-KCH';
  const sheets = setup.sheets
    .filter((sheet) => sheet && REQUIRED_STOCK_SETUP_SECTIONS.includes(String(sheet.sheetName || '').trim()))
    .map((sheet) => ({
      ...sheet,
      sheetName: String(sheet.sheetName || '').trim(),
      rows: Array.isArray(sheet.rows)
        ? sheet.rows.filter((row) => row && String(row.item || '').trim())
        : []
    }))
    .filter((sheet) => sheet.rows.length);

  const found = new Set(sheets.map((sheet) => sheet.sheetName));
  const missing = REQUIRED_STOCK_SETUP_SECTIONS.filter((name) => !found.has(name));
  if (missing.length) throw new Error(`Stock Setup is incomplete: ${missing.join(', ')}`);

  await db.prepare(`CREATE TABLE IF NOT EXISTS stock_setups (
    outlet_id TEXT PRIMARY KEY,
    setup_json TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'excel',
    updated_at INTEGER NOT NULL
  )`).run();
  await db.prepare(`CREATE TABLE IF NOT EXISTS stock_snapshots (
    outlet_id TEXT NOT NULL,
    month_key TEXT NOT NULL,
    snapshot_json TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'd1',
    updated_at INTEGER NOT NULL,
    PRIMARY KEY (outlet_id, month_key)
  )`).run();

  let previous = null;
  try {
    const row = await db.prepare('SELECT setup_json FROM stock_setups WHERE outlet_id = ?').bind(outletId).first();
    previous = row?.setup_json ? JSON.parse(row.setup_json) : null;
  } catch {}

  const candidate = String(setup.outletCode || setup.outletName || setup.outlet || '').trim();
  const displayOutlet = candidate && candidate !== outletId ? candidate : String(previous?.outletCode || previous?.outletName || previous?.outlet || outletId);
  const orderPage = hasOrderPage(setup.orderPage)
    ? setup.orderPage
    : hasOrderPage(previous?.orderPage)
      ? previous.orderPage
      : { values: [] };
  const now = Date.now();
  const normalized = {
    ...setup,
    version: Number(setup.version || 4),
    outletId,
    outletCode: String(setup.outletCode || previous?.outletCode || displayOutlet),
    outletName: String(setup.outletName || previous?.outletName || ''),
    outlet: displayOutlet,
    updatedAt: now,
    importedAt: setup.importedAt || new Date(now).toISOString(),
    sheets,
    orderPage
  };

  await db.prepare(`
    INSERT INTO stock_setups (outlet_id, setup_json, source, updated_at)
    VALUES (?, ?, 'excel', ?)
    ON CONFLICT(outlet_id) DO UPDATE SET
      setup_json = excluded.setup_json,
      source = excluded.source,
      updated_at = excluded.updated_at
  `).bind(outletId, JSON.stringify(normalized), now).run();

  await db.prepare('DELETE FROM stock_snapshots WHERE outlet_id = ?').bind(outletId).run();

  return {
    ok: true,
    saved: true,
    outletId,
    outletCode: normalized.outletCode,
    outletName: normalized.outletName,
    outlet: normalized.outlet,
    setupUpdatedAt: now,
    sheetCount: sheets.length,
    itemCount: sheets.reduce((sum, sheet) => sum + sheet.rows.length, 0),
    orderPageRows: orderPage.values.length,
    dataSource: 'cloudflare-d1-stock-setup-direct'
  };
}

function resolveStockSetupPayload(payload) {
  if (payload.setup && Array.isArray(payload.setup.sheets)) return payload.setup;
  if (payload.setupJson) {
    let parsed;
    try {
      parsed = JSON.parse(String(payload.setupJson));
    } catch {
      throw new Error('Stock Setup JSON could not be read. Export a fresh Stock Setup DB file and import it again.');
    }
    if (parsed && Array.isArray(parsed.sheets)) return parsed;
  }
  throw new Error('Stock Setup data is missing. Re-select the Excel file and import again.');
}

async function decorateStockOutletIdentity(db, payload, data) {
  const result = { ...(data || {}) };
  const outletId = String(payload.outlet || payload.outletId || result.outletId || result.outlet || 'RR-KCH').trim() || 'RR-KCH';
  let setup = result.setup && Array.isArray(result.setup.sheets) ? result.setup : null;
  if (!setup) {
    try {
      const row = await db.prepare('SELECT setup_json FROM stock_setups WHERE outlet_id = ?').bind(outletId).first();
      setup = row?.setup_json ? JSON.parse(row.setup_json) : null;
    } catch {}
  }
  const outletCode = String(setup?.outletCode || result.outletCode || '').trim();
  const outletName = String(setup?.outletName || result.outletName || '').trim();
  const storedOutlet = String(setup?.outlet || '').trim();
  const existing = String(result.outlet || '').trim();
  const display = outletCode || outletName || (storedOutlet && storedOutlet !== outletId ? storedOutlet : '') || (existing && existing !== outletId ? existing : '') || outletId;
  result.outletId = outletId;
  result.outletCode = outletCode;
  result.outletName = outletName;
  result.outlet = display;
  if (setup) result.setup = setup;
  return result;
}

function hasOrderPage(orderPage) {
  return Array.isArray(orderPage?.values) && orderPage.values.length > 0;
}

async function clearStockCounts(db, payload) {
  const outlet = String(payload.outlet || payload.outletId || 'RR-KCH').trim() || 'RR-KCH';
  const monthKey = normalizeMonth(payload.monthKey || payload.businessDate);
  const sectionName = String(payload.sectionName || '').trim();
  const weekIndex = Number(payload.weekIndex || 0);
  const now = Date.now();

  const statements = [];
  if (sectionName && weekIndex > 0) {
    statements.push(db.prepare('DELETE FROM stock_values WHERE outlet_id = ? AND month_key = ? AND sheet_name = ? AND week_index = ?').bind(outlet, monthKey, sectionName, weekIndex));
  } else if (sectionName) {
    statements.push(db.prepare('DELETE FROM stock_values WHERE outlet_id = ? AND month_key = ? AND sheet_name = ?').bind(outlet, monthKey, sectionName));
  } else {
    statements.push(db.prepare('DELETE FROM stock_values WHERE outlet_id = ? AND month_key = ?').bind(outlet, monthKey));
  }
  statements.push(db.prepare('DELETE FROM stock_submissions WHERE outlet_id = ? AND month_key = ?').bind(outlet, monthKey));
  statements.push(db.prepare('DELETE FROM stock_sync_queue WHERE outlet_id = ? AND month_key = ?').bind(outlet, monthKey));
  statements.push(db.prepare('DELETE FROM stock_snapshots WHERE outlet_id = ? AND month_key = ?').bind(outlet, monthKey));
  await db.batch(statements);

  return { ok: true, cleared: true, outlet, monthKey, sectionName, weekIndex, clearedAt: now, dataSource: 'cloudflare-d1' };
}

function normalizeMonth(value) {
  const text = String(value || '');
  const match = /^(\d{4})-(\d{2})/.exec(text);
  if (match) return `${match[1]}-${match[2]}`;
  return new Date().toISOString().slice(0, 7);
}

function withIntegration(data, env, source) {
  return {
    ...(data || {}),
    integration: {
      statvara: env.STATVARA_WEBHOOK_URL ? 'reserved' : 'reserved',
      storageProvider: env.FILE_STORAGE_PROVIDER || 'google_drive',
      stockDataSource: source
    }
  };
}

function cacheDescriptor(service, payload) {
  const action = String(payload.action || '');
  let ttl = 0;
  if (action === 'getStandaloneCashBootstrap' || action === 'getBootstrap') ttl = 90;
  else if (action === 'getStandaloneCashDashboard' || action === 'getStockDashboard') ttl = 45;
  if (!ttl) return null;
  const params = new URLSearchParams({
    service,
    action,
    outlet: String(payload.outlet || ''),
    businessDate: String(payload.businessDate || ''),
    dateFrom: String(payload.dateFrom || ''),
    dateTo: String(payload.dateTo || '')
  });
  return {
    ttl,
    request: new Request(`https://operations-cache.internal/read?${params.toString()}`, { method: 'GET' })
  };
}

async function invalidateBootstrapCache(cache, service, payload) {
  const action = service === 'cash' ? 'getStandaloneCashBootstrap' : 'getBootstrap';
  const params = new URLSearchParams({
    service,
    action,
    outlet: String(payload.outlet || ''),
    businessDate: String(payload.businessDate || ''),
    dateFrom: '',
    dateTo: ''
  });
  await cache.delete(new Request(`https://operations-cache.internal/read?${params.toString()}`, { method: 'GET' }));
}

function json(value, status = 200, ttl = 0) {
  return new Response(JSON.stringify(value), {
    status,
    headers: {
      'Content-Type': 'application/json;charset=utf-8',
      'Cache-Control': ttl > 0 ? `public, max-age=0, s-maxage=${ttl}` : 'no-store'
    }
  });
}
